name: CI verify cleanly generated code
'on':
  workflow_call: null
jobs:
  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4
      - name: Run code gen
        run: cargo run --bin opcua-codegen code_gen_config.yml
      - name: Format generated code
        run: cargo fmt --all
      - name: Verify generated code matches committed code
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "Workspace is not clean, it has not been formatted, or codegen is not up to date"
            git status --porcelain
            exit 1
          fi
